# Laboratorium 4 — NumPy zaawansowane
**Autor:** Marta Machacka

In [2]:
import numpy as np

## Ćwiczenie 1: Broadcasting — zastosowania biznesowe

In [3]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


### Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja). Wyświetl wynik.

In [4]:
ceny_po_inflacji = np.round(ceny * 1.05, 2)
print(ceny_po_inflacji)

[[ 31.49  33.59  30.44]
 [ 52.49  55.64  50.39]
 [ 15.74  16.79  14.69]
 [104.99 110.24  99.74]]


### Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat: Centrum 10%, Galeria 5%, Online 15%.

In [5]:
rabaty = np.array([0.10, 0.05, 0.15])
ceny_po_rabacie = np.round(ceny * (1 - rabaty), 2)
print(ceny_po_rabacie)

[[26.99 30.39 24.64]
 [44.99 50.34 40.79]
 [13.49 15.19 11.89]
 [89.99 99.74 80.74]]


### Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%

In [9]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
# Broadcasting: macierz (4×3) * wektor kolumnowy (4×1)
broadcasting = ceny * marza
#print(broadcasting)
# Oblicz koszt zakupu: cena / (1 + marża)
koszt_zakupu = ceny / (1 + marza)
print(koszt_zakupu)
# Podpowiedź: marża jest kolumną (4×1) — broadcasting kolumnowy

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


### Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [8]:
najtansze_id = np.argmin(ceny, axis = 1)
for i, id in enumerate(najtansze_id):
    print(f"Produkt {produkty[i]}: najtaniej {sklepy[id]}")


Produkt A: najtaniej Online
Produkt B: najtaniej Online
Produkt C: najtaniej Online
Produkt D: najtaniej Online


## Ćwiczenie 2: Reshape i łączenie danych

### Zadanie 2a — Reshape

In [17]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}, suma: {kwartaly.sum(axis=1).max()}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4, suma: 562


### Zadanie 2b — Stacking

In [18]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


## Zadanie 2c — Praktyczne (samodzielnie)

In [22]:
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące

# 1. Reshape na macierz 6×2
# Podpowiedź: sprzedaz_flat.reshape(6, 2) albo .reshape(-1, 2)

sprzedaz_reshape = sprzedaz_flat.reshape(6,2)
print(f"Reshape na macierz 6×2:\n{sprzedaz_reshape}\n")
# 2. Oblicz średnią sprzedaż per produkt (axis=1)

sr_sprzedaz_per_produkt = sprzedaz_reshape.mean(axis = 1)
print(f"Średnia sprzedaż per produkt: \n{sr_sprzedaz_per_produkt}\n")

# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]
roznica = sprzedaz_reshape[:,1] - sprzedaz_reshape[:,0]
print(f"Zmiana między miesiącem 1 a 2: \n{roznica}")

Reshape na macierz 6×2:
[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]

Średnia sprzedaż per produkt: 
[150. 225. 215. 170. 240. 225.]

Zmiana między miesiącem 1 a 2: 
[100 150 -70 100 140 -70]


### Zadanie 2d — Flatten i concatenate

In [25]:
# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())

kwartaly_wektor = kwartaly.flatten()
print(f"Spłaszcona macierz do kwartałów: \n{kwartaly_wektor}\n")

# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
kwartaly_wektor = np.concatenate([kwartaly_wektor, np.array([235])])

# Podpowiedź: np.concatenate([wektor, np.array([235])])
print(f"Dodane dane z 13. miesiąca: \n{kwartaly_wektor}")


Spłaszcona macierz do kwartałów: 
[120 135  98 142 167 189 201 178 156 143 198 221]

Dodane dane z 13. miesiąca: 
[120 135  98 142 167 189 201 178 156 143 198 221 235]


## Ćwiczenie 3: Analiza danych finansowych

In [26]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

### Zadanie 3a: Analiza wynagrodzeń

In [28]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()

srednia = pensje.mean()
mediana = np.median(pensje)
odchylenie = pensje.std()
print(f"Średnia: {srednia} zł\nMediana: {mediana} zł \nOdchylenie standardowe: {odchylenie:.2f}\n")

# 2. Wyświetl imiona osób zarabiających powyżej średniej
# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]

pracownicy = np.array(pracownicy)
osoby_powyzej_mean = pracownicy[pensje > srednia]
osoby = ", ".join(osoby_powyzej_mean)
print(f"Osoby zarabiające powyżej średniej: {osoby}")


# 3. Wyświetl imiona osób zarabiających poniżej mediany
osoby_ponizej_median = pracownicy[pensje < mediana]
osoby = ", ".join(osoby_ponizej_median)
print(f"Osoby zarabiające poniżej mediany: {osoby}")

# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)
rozstep = pensje.max() - pensje.min()
print(f"Rozstęp: {rozstep} zł")
irq = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(f"Rozstęp międzykwartylowy (IQR): {irq} zł")

Średnia: 6425.0 zł
Mediana: 6050.0 zł 
Odchylenie standardowe: 1616.90

Osoby zarabiające powyżej średniej: Jan, Marek, Zofia
Osoby zarabiające poniżej mediany: Anna, Ewa, Piotr, Tomek
Rozstęp: 4900 zł
Rozstęp międzykwartylowy (IQR): 2200.0 zł


## Zadanie 3b: System premii (np.where)

In [33]:
# Zasady premii:
# - ocena >= 4.5 → premia 2000 zł
# - ocena >= 4.0 → premia 1000 zł
# - ocena < 4.0 → premia 0 zł
# Podpowiedź: zagnieżdżony where:
#   np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))

premia = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))

# Oblicz nowe wynagrodzenie (pensja + premia)

nowe_wynagrodzenie = pensje + premia
print("---Nowe wynagrodzenia---")
for imie, n_wynagr in zip(pracownicy, nowe_wynagrodzenie):
    print(f"{imie}: {n_wynagr}zł")
# Kto dostał najwyższą premię? Użyj argmax()
indeks_max = premia.argmax()       
max_premia = premia[indeks_max]  
wszyscy_z_max_premia = [pracownicy[i] for i, p in enumerate(premia) if p == max_premia]
wszyscy_z_max_premia = ", ".join(wszyscy_z_max_premia)
print(f"\nNajwyższa premia: {wszyscy_z_max_premia}")


---Nowe wynagrodzenia---
Anna: 6500zł
Jan: 7200zł
Ewa: 6800zł
Marek: 10100zł
Kasia: 8300zł
Piotr: 4200zł
Zofia: 9500zł
Tomek: 5800zł

Najwyższa premia: Ewa, Kasia


### Zadanie 3c: Ranking (argsort)

In [35]:
# Posortuj pracowników wg pensji (od najwyższej)
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]

kolejnosc = np.argsort(pensje)[::-1]
pracownicy_posortowani = [pracownicy[i] for i in kolejnosc]
print(f"Pracownicy wg pensji: {', '.join(pracownicy_posortowani)}\n")

# Wyświetl ranking: pozycja, imię, pensja, staż
# Podpowiedź: for i, idx in enumerate(kolejnosc, 1): ...
print(f"--- Ranking ---")
for i, idx in enumerate(kolejnosc, 1):
    print(f"{i}. {pracownicy[idx]} – pensja: {pensje[idx]} zł, staż: {staz[idx]} lat")


Pracownicy wg pensji: Marek, Zofia, Jan, Kasia, Tomek, Anna, Ewa, Piotr

--- Ranking ---
1. Marek – pensja: 9100 zł, staż: 15 lat
2. Zofia – pensja: 8500 zł, staż: 12 lat
3. Jan – pensja: 7200 zł, staż: 8 lat
4. Kasia – pensja: 6300 zł, staż: 5 lat
5. Tomek – pensja: 5800 zł, staż: 4 lat
6. Anna – pensja: 5500 zł, staż: 3 lat
7. Ewa – pensja: 4800 zł, staż: 2 lat
8. Piotr – pensja: 4200 zł, staż: 1 lat


### Zadanie 3d: Korelacja

In [37]:
# Oblicz korelację: staż vs pensja
# Podpowiedź: np.corrcoef(staz, pensje)[0, 1]

korelacja_s_vs_p = np.corrcoef(staz, pensje)[0, 1]

# Oblicz korelację: staż vs ocena
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)
korelacja_s_sv_o = np.corrcoef(staz, oceny)[0, 1]

if korelacja_s_vs_p > korelacja_s_sv_o:
    print(f"Korelacja: staż vs pensja jest silniejsza")
elif korelacja_s_vs_p < korelacja_s_sv_o:
    print("Korelacja: staż vs ocena jest silniejsza")
else:
    print("Są sobie równe")

Korelacja: staż vs pensja jest silniejsza


### Zadanie 3e: Analiza sprzedaży (broadcasting)

In [38]:
# Oblicz przychód: sprzedaz (4×6) * ceny_produktow (4,) — UWAGA na broadcasting!
# Problem: (4,6) * (4,) — nie pasuje! 6 != 4
# Rozwiązanie: ceny muszą być kolumną (4×1)
# Podpowiedź: ceny_kol = ceny_produktow.reshape(4, 1)
#             przychod = sprzedaz * ceny_kol

ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)

suma_poruktow = przychod.sum(axis=1)
indeks_max_produkt = suma_poruktow.argmax()
print(f"Produkt z największym przychodem: {produkty_nazwy[indeks_max_produkt]}")

# Który miesiąc był najlepszy łącznie? (axis=0, argmax)

suma_miesiace = przychod.sum(axis=0)
najleprzy_miesiac = suma_miesiace.argmax() + 1
print(f"Najlepszy miesiąc: {najleprzy_miesiac}")

# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
# Podpowiedź: przychod[:, :3].sum() vs przychod[:, 3:].sum()
pierwsze_trzy_miesace = przychod[:, :3].sum() 
ostatnie_trzy_miesiace = przychod[:, 3:].sum()

if pierwsze_trzy_miesace > ostatnie_trzy_miesiace:
    print("Pierwsze 3 miesiące przyniosły większy przychód")
elif ostatnie_trzy_miesiace > pierwsze_trzy_miesace:
    print("Ostatnie 3 miesiące przyniosły większy przychód")
else:
    print("Przychód w pierwszych i ostatnich 3 miesiącach był taki sam")

Produkt z największym przychodem: Smartfon
Najlepszy miesiąc: 2
Ostatnie 3 miesiące przyniosły większy przychód


## Ćwiczenie 4: Generowanie danych

### Krok 1 — Generowanie

In [39]:
np.random.seed(42)

# Wygeneruj dane o 100 klientach sklepu:
# - wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
# - wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
# - liczba_wizyt: rozkład Poissona, lambda=5

# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

### Krok 2 — Analiza

In [ ]:
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
# Podpowiedź: print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")

print(f"Wiek - średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.2f}, min: {wiek.min()}, max: {wiek.max()}")

# 2. Korelacja wiek vs wydatki
# Podpowiedź: np.corrcoef(wiek, wydatki)[0, 1]

print(f"Korelacja wiek vs wydatki: {np.corrcoef(wiek, wydatki)[0,1]}")

# 3. Korelacja wizyty vs wydatki

print(f"Korelacja wiek vs wydatki: {np.corrcoef(wizyty, wydatki)[0,1]}")

# 4. Segmentacja klientów za pomocą np.where:
#    - "WYSOKI" gdy wydatki > średnia + std
#    - "NISKI" gdy wydatki < średnia - std
#    - "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
#   sr = wydatki.mean()
#   sd = wydatki.std()
#   segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

sr = wydatki.mean()
sd = wydatki.std()
#segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

warunki = [wydatki > sr + sd, wydatki >= sr - sd, wydatki < sr - sd]
wartosci = ['WYSOKI', 'ŚREDNI', 'NISKI']
segment = np.select(warunki, wartosci, default= 'ŚREDNIE')

# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)
print(f"--- SEGMENTY ---")
unikaty, ilosc = np.unique(segment, return_counts=True)
procenty = ilosc / len(segment) * 100

for seg, il, p in zip(unikaty, ilosc, procenty):
    print(f"{seg}: {il} klientów ({p:.1f}%)")

Wiek - średnia: 33.6, mediana: 33.0, std: 8.64, min: 18, max: 53
Korelacja wiek vs wydatki: -0.1201
Korelacja wiek vs wydatki: -0.1588
--- SEGMENTY ---
NISKI: 17 klientów (17.0%)
WYSOKI: 12 klientów (12.0%)
ŚREDNI: 71 klientów (71.0%)
