# Laboratorium 3 - NumPy
**Autor:** Marta Machacka

## Ćwiczenie 1: Tworzenie tablic

In [2]:
import numpy as np

In [3]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [5]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3,5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [9]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")


Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [10]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size = 20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


## Atrybuty

In [11]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


## Ćwiczenie 2: Indeksowanie i sclicing

### Część A - Tablica 1D

In [ ]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

**Zadania**

1. Sprzedaż w styczniu

In [13]:
print(miesiace_sprzedaz[0])

120


2. Sprzedaż w grudniu:

In [14]:
print(miesiace_sprzedaz[-1])

221


3. Sprzedaż w Q1

In [24]:
print(miesiace_sprzedaz[0:3])
print(f"Syma sprzedaży w Q1: {miesiace_sprzedaz[0:3].sum()}")

[120 135  98]
Syma sprzedaży w Q1: 353


4. Sprzedaż w Q4

In [26]:
print(miesiace_sprzedaz[-3:])
print(f"Suma sprzedaży w Q4: {miesiace_sprzedaz[-3:].sum()}")

[143 198 221]
Suma sprzedaży w Q4: 562


5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj, ...):

In [27]:
print(miesiace_sprzedaz[::2])
print(f"Suma sprzedaży w co drugim miesiącu: {miesiace_sprzedaz[::2].sum()}")

[120  98 167 201 156 198]
Suma sprzedaży w co drugim miesiącu: 940


6. Sprzedaż od tyłu (grudzień → styczeń)

In [28]:
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


### Część B - Macierz 2D

In [3]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

**Zadania:**

1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):

In [31]:
print(dane[0,1])

145


2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny) 

In [37]:
print(dane[2,:])
print(f"Sprzedaż całkowita: {dane[2,:].sum()}")

[234 267 289]
Sprzedaż całkowita: 790


3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):

In [40]:
print(dane[:,0])

[120  89 234  56]


4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):

In [42]:
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


## Ćwiczenie 3: Operacje wektorowe - analiza biznesowa
### Cel
Użyj operacji NumPy do rozwiązania problemów biznesowych. Samodzielna praca.

### Dane

In [3]:
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

### Zadania

**Zadanie 1:** Podstawowe statystyki cenowe

In [4]:
print(f"Średnia cena: {ceny.mean()} zł")
print(f"Najdroższy produkt: {ceny.max()} zł")
print(f"Najtańszy produkt: {ceny.min()} zł")
print(f"Odchylenie standardowe: {ceny.std():.2f} zł")



Średnia cena: 1171.0 zł
Najdroższy produkt: 3499 zł
Najtańszy produkt: 89 zł
Odchylenie standardowe: 1095.63 zł


In [34]:
nazwy = np.array(nazwy)
print(f"Najdroższy produkt: {nazwy[ceny.argmax()]}")
print(f"Najtańszy produkt: {nazwy[ceny.argmin()]}")

Najdroższy produkt: Laptop
Najtańszy produkt: Ładowarka


**Zadanie 2:** Wartość magazynu

In [36]:
wartosc_produktow = ceny * ilosci_magazyn
for n, wp in zip(nazwy, wartosc_produktow):
    print(f"{n} łączna wartość na magazynie: {wp} zł")
print(f"Wartość magazynu: {np.sum(ceny * ilosci_magazyn)} zł")

Laptop łączna wartość na magazynie: 52485 zł
Tablet łączna wartość na magazynie: 79758 zł
Smartfon łączna wartość na magazynie: 194922 zł
Słuchawki łączna wartość na magazynie: 54444 zł
Ładowarka łączna wartość na magazynie: 27768 zł
Klawiatura łączna wartość na magazynie: 22161 zł
Mysz łączna wartość na magazynie: 25929 zł
Monitor łączna wartość na magazynie: 34477 zł
Kamera łączna wartość na magazynie: 26955 zł
Drukarka łączna wartość na magazynie: 30566 zł
Wartość magazynu: 549465 zł


**Zadanie 3:** Analiza cenowa

#### Ceny po rabacie 15% (promocja świąteczna)

In [45]:
promocja_swiateczna = ceny * 0.85

for nazwa, cena in zip(nazwy, promocja_swiateczna):
    print(f"{nazwa}: {cena:.2f} zł")

Laptop: 2974.15 zł
Tablet: 1614.15 zł
Smartfon: 2124.15 zł
Słuchawki: 296.65 zł
Ładowarka: 75.65 zł
Klawiatura: 211.65 zł
Mysz: 109.65 zł
Monitor: 1274.15 zł
Kamera: 509.15 zł
Drukarka: 764.15 zł


#### Ceny z VAT 23%

In [18]:
ceny_z_vat = ceny * 1.23
for nazwa, cena in zip(nazwy, ceny_z_vat):
    print(f"{nazwa}: {cena:.2f} zł")

Laptop: 4303.77 zł
Tablet: 2335.77 zł
Smartfon: 3073.77 zł
Słuchawki: 429.27 zł
Ładowarka: 109.47 zł
Klawiatura: 306.27 zł
Mysz: 158.67 zł
Monitor: 1843.77 zł
Kamera: 736.77 zł
Drukarka: 1105.77 zł


#### Ile produktów kosztuje powyżej 1000 zł?

In [19]:
#licznik = 0
#for cena in ceny:
#    if cena > 1000:
#        licznik +=1
#    else: 
#        continue

#print(f"Ilość produktów powyżej 1000 zł: {licznik}")
print(f"Ilość produktów powyżej 1000 zł: {(ceny > 1000).sum()}")

Ilość produktów powyżej 1000 zł: 4


**Zadanie 4:** Filtrowanie

#### Produkty z oceną >= 4.5 — nazwy i ceny

In [37]:
nazwy = np.array(nazwy)
maska = oceny_klientow >= 4.5
nazwy_wybrane = nazwy[maska]
ceny_wybrane = ceny[maska]
for n, c in zip(nazwy_wybrane, ceny_wybrane):
    print(f"{n}: {c} zł")

Laptop: 3499 zł
Smartfon: 2499 zł
Słuchawki: 349 zł
Monitor: 1499 zł


#### Produkty poniżej 200 zł — nazwy i ilości w magazynie

In [8]:
nazwy = np.array(nazwy)
maska = ceny < 200
ceny_ponizej = ceny[maska]
nazwy_ponizej = nazwy[maska]
ilosc_ponizej = ilosci_magazyn[maska]
for c, n, i in zip(ceny_ponizej, nazwy_ponizej, ilosc_ponizej):
    print(f"{n}: {c} zł, {i} sztuk")

Ładowarka: 89 zł, 312 sztuk
Mysz: 129 zł, 201 sztuk


**Zadanie 5:** Analiza zapasów

#### Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy

In [9]:
maska = ilosci_magazyn < 30
nazwy = np.array(nazwy)
produkty_niski_stan = nazwy[maska]
ilosc_na_stanie_niski_stan = ilosci_magazyn[maska]
print("Produkty z niskim stanem magazynowym:")
for p, i in zip(produkty_niski_stan, ilosc_na_stanie_niski_stan):
    print(f"- {p} x {i}")

Produkty z niskim stanem magazynowym:
- Laptop x 15
- Monitor x 23


#### Łączna wartość tych produktów

In [ ]:
ceny_niski_stan = ceny[maska]
#print(ceny_niski_stan)
print(f"Łączna wartość produktów, \nktórych stan magazynowych jest niski: \n {(ilosc_na_stanie_niski_stan * ceny_niski_stan).sum()}")


[3499 1499]
Łączna wartość produktów, 
których stan magazynowych jest niski: 
 86962


#### Ile % całego magazynu stanowią?

In [44]:
caly_magazyn = (ceny * ilosci_magazyn).sum()
#print(caly_magazyn)
procent_magazynu = ((ilosc_na_stanie_niski_stan * ceny_niski_stan).sum()/caly_magazyn)*100
print(f"ile % warości całego magazynu: {procent_magazynu:.2f}%")

ile % warości całego magazynu: 15.83%


####

**Zadanie 6 (bonus):** Analiza korelacji cena–ocena

#### Które produkty są "okazją" — ocena >= 4.5 
#### i cena < 1000 zł? Wypisz nazwy i ceny.

In [26]:
warunek1 = oceny_klientow >=4.5
warunek2 = ceny < 1000
wynik = nazwy[warunek1 & warunek2]
print(wynik)


['Słuchawki']


#### Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?

In [30]:
sr_wieksza = oceny_klientow >= 4.0
sr_mniejsza = oceny_klientow < 4.0
wynik_mniejsza = ceny[sr_mniejsza].mean()
wynik_wieksza = ceny[sr_wieksza].mean()
print(f"Średnia cena przy ocenie 4.0 i wyżej: {wynik_wieksza:.2f} zł \nŚrednia cena przy ocenie niższej od 4.0: {wynik_mniejsza:.2f} zł")


Średnia cena przy ocenie 4.0 i wyżej: 1446.14 zł 
Średnia cena przy ocenie niższej od 4.0: 529.00 zł


## Ćwiczenie 4: Benchmark — lista vs NumPy (15 min) 

In [37]:
import time
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [38]:
# Test 1: Pomnóż przez 2
5
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 96.8 ms
NumPy: 4.4 ms
NumPy jest 22× szybszy!


In [41]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 16.6 ms
NumPy: 1.9 ms
NumPy jest 9× szybszy!


In [42]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 68.7 ms
NumPy: 3.3 ms
NumPy jest 21× szybszy!


## Wnioski z benchmarku
- NumPy jest **22×** szybszy w mnożeniu
- NumPy jest **9×** szybszy w sumowaniu
- NumPy jest **21×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list